version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie

    steps:
      - checkout      
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
       
      - run:
          name: Install npm wee
          command: npm install
          
      - run:
          name: Print the Current Time
          command: date
